scoring_configs:
  - name: tone-scoring-config
    subtype: categorical
    options:
      - "positive"
      - "neutral"
      - "negative"
  - name: job-quality-num-scoring-config
    subtype: continuous
    min: 0
    max: 5
    inclusive_min: True
    inclusive_max: False
  - example_rubrics/my_tiered_scoring_config.yaml
